### ISSUE TITLE
Port to sd-bus

### ISSUE THREAD

**Issue by vodik** [vodik/envoy#47]
This will unfortunately set a hard dep on systemd>=221, so care must be taken to be somewhat backwards compatible.

**Comment by vodik** [comment]
Alright, nobody is complaining about the implementation, so I'm going to assume its a success.

**Comment by EvanPurkhiser** [comment]
I was playing around with seeing if I could get envoy working as a user service. I have the service file

```ini
[Unit]
Description=Envoy agent monitor for %i
Documentation=man:envoyd(1) man:envoy(1)

[Service]
ExecStart=/usr/bin/envoyd -t %i
StandardOutput=syslog
StandardError=syslog
Environment=GNUPGHOME=${HOME}/.config/gnupg

[Install]
WantedBy=default.target
Also=envoy@.socket
```

When starting the service `systemctl start envoy@gpg-agent` systemctl hangs and I see lots of this going on in my journal:

```
Jul 19 04:02:07 desktop.home.evanpurkhiser.com systemd[300]: Looping too fast. Throttling execution a little.
Jul 19 04:02:08 desktop.home.evanpurkhiser.com systemd[300]: Looping too fast. Throttling execution a little.
Jul 19 04:02:09 desktop.home.evanpurkhiser.com systemd[300]: Looping too fast. Throttling execution a little.
Jul 19 04:02:10 desktop.home.evanpurkhiser.com systemd[300]: Looping too fast. Throttling execution a little.
Jul 19 04:02:11 desktop.home.evanpurkhiser.com systemd[300]: Looping too fast. Throttling execution a little.
```

If I terminate the `systemctl` command the service starts up (I still see a lot of those warnings though).

Running `envoy` to get my agent up yields this:

```
Jul 19 04:09:27 desktop.home.evanpurkhiser.com envoyd[4104]: Starting gpg-agent for uid=1000.
Jul 19 04:09:27 desktop.home.evanpurkhiser.com envoyd[4104]: envoyd: unable to drop permissions to uid=1000 gid=100
Jul 19 04:09:27 desktop.home.evanpurkhiser.com envoyd[4104]: : Operation not permitted
Jul 19 04:09:27 desktop.home.evanpurkhiser.com envoyd[4104]: gpg-agent exited with status 1.
```

Can't say for sure that it's related to this implementation. But this is on `14.8.g67079db-1`.

**Comment by blueyed** [comment]
@EvanPurkhiser 
If this is still a problem, please consider reporting it as a separate issue.
