### ISSUE TITLE
missing-call-to-setgroups-before-setuid

### ISSUE THREAD

**Issue by zdzichu** [vodik/envoy#49]
rpmlint complains:

 E: missing-call-to-setgroups-before-setuid /usr/lib64/security/pam_envoy.so
 E: missing-call-to-setgroups-before-setuid /usr/bin/envoyd

This has potential security implications: 
_This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this mean it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem._

**Comment by jotrk** [comment]
Came here to open an issue for the same problem.
Not sure if it's bogus or not, but +1.

**Comment by vodik** [comment]
Thank you very much!
