### ISSUE TITLE
Failed to chmod: No such file or directory

### ISSUE THREAD

**Issue by terlar** [vodik/envoy#52]
I have just installed the latest envoy from git and now I get the following error when I try to start `envoy@gpg-agent.service`:
```
envoyd[464]: envoyd: failed to chmod: No such file or directory
```

After this the service fails and terminates.

**Comment by vodik** [comment]
Sigh, see #53...

I know what I did though.

**Comment by vodik** [comment]
Welp, looks like that code never worked. Thanks for the catch.

**Comment by terlar** [comment]
No problem, I was unsure if I did something wrong myself. Thank you for the quick fix :)

I really feel the power of envoy now when I had the inconvenience to have to do that GPG agent stuff manually. Great tool!
