### ISSUE TITLE
gpg-agent no longer prompts with pinentry for ssh keys

### ISSUE THREAD

**Issue by holomorph** [vodik/envoy#54]
The gnupg update from `2.1.7-1 -> 2.1.8-2` appears to be the culprit.

**Comment by holomorph** [comment]
nvm, upstream issue https://lists.gnupg.org/pipermail/gnupg-devel/2015-September/030289.html

**Comment by vodik** [comment]
Noted, thanks. Sorry, just got back from vacation.
