### ISSUE TITLE
gpg-agent backend fails if $GNUPGHOME is set

### ISSUE THREAD

**Issue by BrainDamage** [vodik/envoy#57]
envoy fails to connect to gpg-agent backend if $GNUPGHOME is set with the following error:
```envoy: failed to connect to GPG_AUTH_SOCK: No such file or directory```
from a cursory inspection of the code, it seems that envoy.c calls everywhere
```gpg_agent_connection(data->gpg, NULL)```
and from gpg-protocol.rl we get:
```struct gpg_t *gpg_agent_connection(const char *sock, const char *home)```
...
```       len = snprintf(sa.un.sun_path, sizeof(sa.un.sun_path),
                       "%s/.gnupg/S.gpg-agent",
                       home ? home : get_home_dir())```

this howrever is incorrect twice:
* it ignores the env var that sets gnupg home
* even if it'd read $GNUPGHOME were it set, it'd generate a socket path path along the lines of "$GNUPGHOME/.gnupg/S.gpg-agent", while if set it should actually generate "$GNUPGHOME/S.gpg-agent" if set and "$HOME/.gnupg/S.gpg-agent" if not set

**Comment by vodik** [comment]
Noted! Indeed that's an issue. I'll have to think a little big about how to correct that.

**Comment by vodik** [comment]
Merged it into master.
