### ISSUE TITLE
systemd 229

### ISSUE THREAD

**Issue by holomorph** [vodik/envoy#70]
libsystemd-daemon doesn't exist anymore

**Comment by oschwede** [comment]
Workaround (at least for Arch Linux):
sed -i 's/libsystemd-daemon/libsystemd/g' Makefile

**Comment by vodik** [comment]
Hey, thanks! Sorry, I've been taking a break from my projects to recoup my energies.

**Comment by holomorph** [comment]
thanks o/

**Comment by vodik** [comment]
Right, forgot to close this. Thanks
